/** Validation case C11 (golden fixture): three-slot heterogeneous deal, file pricing. Generated from utica_fixtures/C11/L00_inputs.json. */
import type { DealInputs, SlotInput } from "../../engine/index";
export const C11_NAME = "Validation Case C11";
/** Expected at display precision: IRR 35.6% (engine full life; Python 360-month reference 35.6%), MOIC 2.10x (Python reference 2.09x). */
export const C11_DEAL: DealInputs = {
  "effectiveDate": "2026-10-01",
  "pricingMode": "file",
  "oilPrice": 70,
  "gasPrice": 3.75,
  "baseOilPrice": 70,
  "baseGasPrice": 3.75,
  "oilFlatStartDate": "2030-09-01",
  "gasFlatStartDate": "2029-01-01",
  "useDcOverride": false,
  "dcOverride": 750,
  "useBidOverride": false,
  "bidOverride": 8000,
  "useCarryOverride": false,
  "carryOverridePct": 20,
  "useSevTaxPct": false,
  "oilSevTax": 0.1,
  "gasSevTax": 0.025,
  "adValTax": 0.025,
  "ethaneRec": false,
  "content": {
    "ethane": 0.5,
    "propane": 0.25,
    "isobutane": 0.065,
    "butane": 0.065,
    "pentanes": 0.12
  },
  "recoverEthane": {
    "ethane": 0.9,
    "propane": 0.98,
    "isobutane": 0.99,
    "butane": 0.99,
    "pentanes": 0.995
  },
  "rejectEthane": {
    "ethane": 0.2,
    "propane": 0.9,
    "isobutane": 0.98,
    "butane": 0.98,
    "pentanes": 0.995
  },
  "nglShrink": {
    "ethane": 0.06634,
    "propane": 0.091563,
    "isobutane": 0.09963,
    "butane": 0.103744,
    "pentanes": 0.10968
  },
  "nglPrices": {
    "ethane": 0.2345,
    "propane": 0.82528,
    "isobutane": 0.7602,
    "butane": 0.61473,
    "pentanes": 1.28987
  },
  "daleInitialInterestPct": 6.25,
  "promoteEnabled": false,
  "promoteWiReversionPct": 6.25,
  "promoteMultiple": 1.0
};
export const C11_SLOTS: SlotInput[] = [
  {
    "dalePromote": false,
    "daleUnitId": "UNIT-1",
    "dalePayoutGroup": "UNIT-1",
    "daleFirstWellCarry": false,
    "carryEnabled": false,
    "carryWiReversionPct": 0,
    "slotId": 1,
    "tcName": "1_north_cond_north",
    "grossWells": 1,
    "netAcres": 30,
    "unitAcres": 240,
    "useCalcUnitAcres": false,
    "pctUnitized": 1,
    "drillingSpudMonth": "2026-10-01",
    "flowbackDelay": 4,
    "netRevenueInterest": 0.8,
    "lateralLength": 15000,
    "dcCosts": 700,
    "tcRisk": 0.9,
    "bidPerAcre": 7000,
    "oilDiff": -10,
    "gasDiff": -2.75,
    "oilOpexBbl": 1.78,
    "gasOpexMcf": 0.25,
    "nglOpex": 2.5,
    "fixedLoe": 3534,
    "nglYield": 3.5
  },
  {
    "dalePromote": false,
    "daleUnitId": "UNIT-2",
    "dalePayoutGroup": "UNIT-2",
    "daleFirstWellCarry": false,
    "carryEnabled": false,
    "carryWiReversionPct": 0,
    "slotId": 2,
    "tcName": "14_core_rich_condensate_north",
    "grossWells": 1,
    "netAcres": 25,
    "unitAcres": 200,
    "useCalcUnitAcres": false,
    "pctUnitized": 1,
    "drillingSpudMonth": "2027-01-01",
    "flowbackDelay": 4,
    "netRevenueInterest": 0.8,
    "lateralLength": 15000,
    "dcCosts": 750,
    "tcRisk": 1,
    "bidPerAcre": 8000,
    "oilDiff": -10,
    "gasDiff": -2.75,
    "oilOpexBbl": 1.78,
    "gasOpexMcf": 0.25,
    "nglOpex": 2.5,
    "fixedLoe": 3534,
    "nglYield": 4.2
  },
  {
    "dalePromote": false,
    "daleUnitId": "UNIT-3",
    "dalePayoutGroup": "UNIT-3",
    "daleFirstWellCarry": false,
    "carryEnabled": false,
    "carryWiReversionPct": 0,
    "slotId": 3,
    "tcName": "7_core_condensate_north",
    "grossWells": 1,
    "netAcres": 20,
    "unitAcres": 180,
    "useCalcUnitAcres": false,
    "pctUnitized": 1,
    "drillingSpudMonth": "2027-04-01",
    "flowbackDelay": 4,
    "netRevenueInterest": 0.8,
    "lateralLength": 11000,
    "dcCosts": 800,
    "tcRisk": 1.1,
    "bidPerAcre": 9000,
    "oilDiff": -10,
    "gasDiff": -2.75,
    "oilOpexBbl": 1.78,
    "gasOpexMcf": 0.25,
    "nglOpex": 2.5,
    "fixedLoe": 3534,
    "nglYield": 5
  }
];
